version: '2'
services:
  coturn:
    build: .
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

